import type { Config } from 'tailwindcss'
import colors from 'tailwindcss/colors'

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  purge: {
    content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
    options: {
      safelist: [
        'bg-gray-400',
        'bg-red-500',
        'bg-blue-500',
        'bg-yellow-400',
        'bg-green-500',
        'bg-blue-300',
        'bg-red-700',
        'bg-purple-500',
        'bg-yellow-700',
        'bg-indigo-400',
        'bg-pink-500',
        'bg-green-700',
        'bg-yellow-800',
        'bg-purple-800',
        'bg-indigo-700',
        'bg-gray-800',
        'bg-gray-600',
        'bg-pink-300',
        'bg-gradient-to-br',
        'from-gray-400',
        'from-red-500',
        'from-blue-500',
        'from-yellow-400',
        'from-green-500',
        'from-blue-300',
        'from-red-700',
        'from-purple-500',
        'from-yellow-700',
        'from-indigo-400',
        'from-pink-500',
        'from-green-700',
        'from-yellow-800',
        'from-purple-800',
        'from-indigo-700',
        'from-gray-800',
        'from-gray-600',
        'from-pink-300',
        'to-gray-400',
        'to-red-500',
        'to-blue-500',
        'to-yellow-400',
        'to-green-500',
        'to-blue-300',
        'to-red-700',
        'to-purple-500',
        'to-yellow-700',
        'to-indigo-400',
        'to-pink-500',
        'to-green-700',
        'to-yellow-800',
        'to-purple-800',
        'to-indigo-700',
        'to-gray-800',
        'to-gray-600',
        'to-pink-300',
      ],
    },
  },
  theme: {
    colors: {
      primary: '#F2B807',
      secondary: '#F28F16',
      third: '#F5DB13',
      danger: '#D93E30',
      paragraph: '#212121',
      primaryButton: '#73D677',
      normal: 'gray-400',
      fire: 'red-500',
      water: 'blue-500',
      electric: 'yellow-400',
      grass: 'green-500',
      ice: 'blue-300',
      fighting: 'red-700',
      poison: 'purple-500',
      ground: 'yellow-700',
      flying: 'indigo-400',
      psychic: 'pink-500',
      bug: 'green-700',
      rock: 'yellow-800',
      ghost: 'purple-800',
      dragon: 'indigo-700',
      dark: 'gray-800',
      steel: 'gray-600',
      fairy: 'pink-300',
      ...colors,
    },
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
export default config
